"""Length and shape limits for copy rendered directly in an Area room."""

DISPLAY_LINE_PATTERN = r"^[^\r\n]+$"
ASK_TEXT_MAX_CHARS = 160
ASK_DETAIL_MAX_CHARS = 200
REPORT_MAX_CHARS = 240
NEXT_CHECK_REASON_MAX_CHARS = 180
OUTCOME_TITLE_MAX_CHARS = 160
SUCCESS_CRITERIA_MAX_CHARS = 500
WORK_TEXT_MAX_CHARS = 280
EVIDENCE_SUMMARY_MAX_CHARS = 280
