"""Common Markdown wiki pages and revision-backed wiki operations."""

from .approval_store import (
    PendingWikiRenameApprovalConflictError,
    WikiRenameApproval,
    WikiRenameApprovalStatus,
    WikiRenameApprovalStore,
)
from .approvals import (
    CorruptWikiRenameApprovalError,
    RenamePolicy,
    WikiRenameApprovalCoordinator,
    WikiRenameCoordinatorResult,
)
from .models import (
    GeneratedPageTarget,
    LinkReference,
    LinkStatus,
    RenamePlan,
    RenameRewrite,
    WikiChangeCommit,
    WikiChangesReport,
    WikiChangeWarning,
    WikiFactCitation,
    WikiInfrastructureRole,
    WikiLinkReport,
    WikiPageRecord,
    WikiPageRevision,
    WikiResourceChange,
    WikiSnapshot,
)
from .pages import (
    PageValidationError,
    WikiPage,
    create_page,
    extract_generated_region,
    parse_page,
    update_generated_region,
    update_page_metadata,
    update_page_title,
)
from .service import GeneratedRegionConflictError, WikiAmbiguityError, WikiService, WikiValidationError

__all__ = [
    "CorruptWikiRenameApprovalError",
    "GeneratedPageTarget",
    "GeneratedRegionConflictError",
    "LinkReference",
    "LinkStatus",
    "PageValidationError",
    "PendingWikiRenameApprovalConflictError",
    "RenamePlan",
    "RenamePolicy",
    "RenameRewrite",
    "WikiAmbiguityError",
    "WikiChangeCommit",
    "WikiChangeWarning",
    "WikiChangesReport",
    "WikiFactCitation",
    "WikiInfrastructureRole",
    "WikiLinkReport",
    "WikiPage",
    "WikiPageRecord",
    "WikiPageRevision",
    "WikiRenameApproval",
    "WikiRenameApprovalCoordinator",
    "WikiRenameApprovalStatus",
    "WikiRenameApprovalStore",
    "WikiRenameCoordinatorResult",
    "WikiService",
    "WikiSnapshot",
    "WikiResourceChange",
    "WikiValidationError",
    "create_page",
    "extract_generated_region",
    "parse_page",
    "update_generated_region",
    "update_page_metadata",
    "update_page_title",
]
