from collections.abc import Callable

from pydantic import BaseModel, Field


class AutomationDescriptionUnavailableError(RuntimeError):
    """Raised when a concise user-facing automation description cannot be generated."""


class AutomationDescriptionDraft(BaseModel):
    description: str = Field(min_length=1, max_length=220)


_SYSTEM = """Write the concise, user-facing description for one automation.

Return one plain sentence (at most 220 characters) explaining what it does. It
appears beneath the automation title, not in its instructions editor. Do not
copy the full prompt, mention implementation details, schedules, or say
\"automation\". Preserve the user's intent and concrete subject."""


class AutomationDescriptionGenerator:
    """One structured, cheap-model call for display copy.

    This is deliberately not a string heuristic: an omitted description is
    either generated by the configured model or reported as unavailable.
    """

    def __init__(self, *, get_cheap_llm: Callable[[], object | None], model: str | None):
        self._get_cheap_llm = get_cheap_llm
        self._model = model

    async def generate(self, *, name: str, prompt: str) -> str:
        llm = self._get_cheap_llm()
        if llm is None or not self._model:
            raise AutomationDescriptionUnavailableError(
                "A concise description is required while the summary model is unavailable."
            )
        try:
            response = await llm.completion(
                messages=[
                    {"role": "system", "content": _SYSTEM},
                    {"role": "user", "content": f"Title: {name}\n\nInstructions:\n{prompt}"},
                ],
                model=self._model,
                response_format=AutomationDescriptionDraft,
            )
            content = response.choices[0].message.content
            draft = content if isinstance(content, AutomationDescriptionDraft) else AutomationDescriptionDraft.model_validate_json(content)
            description = draft.description.strip()
            if not description:
                raise ValueError("empty description")
            return description
        except AutomationDescriptionUnavailableError:
            raise
        except Exception as exc:
            raise AutomationDescriptionUnavailableError("Could not generate a concise automation description.") from exc
